; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ebc -verify-machineinstrs < %s \
; RUN:  | FileCheck %s -check-prefix=EBC

define i64 @bare_select(i1 %a, i64 %b, i64 %c) {
; EBC-LABEL: bare_select:
; EBC:       ; %bb.0:
; EBC-NEXT:    movqw r0, r0 (0,-32)
; EBC-NEXT:    push64 r1
; EBC-NEXT:    push64 r2
; EBC-NEXT:    push64 r3
; EBC-NEXT:    movqw r7, r0 (0,40)
; EBC-NEXT:    movqq r2, @r7
; EBC-NEXT:    moviww r7, 1
; EBC-NEXT:    and64 r2, r7
; EBC-NEXT:    movqw r1, r0 (0,56)
; EBC-NEXT:    movqw r7, r0 (0,48)
; EBC-NEXT:    moviww r3, 0
; EBC-NEXT:    cmp64eq r2, r3
; EBC-NEXT:    jmp64cc LBB0_2
; EBC-NEXT:  ; %bb.1:
; EBC-NEXT:    movqq r7, r1
; EBC-NEXT:  LBB0_2:
; EBC-NEXT:    movqq r7, @r7
; EBC-NEXT:    pop64 r3
; EBC-NEXT:    pop64 r2
; EBC-NEXT:    pop64 r1
; EBC-NEXT:    movqw r0, r0 (0,32)
; EBC-NEXT:    ret
  %1 = select i1 %a, i64 %b, i64 %c
  ret i64 %1
}
