; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ebc -verify-machineinstrs < %s \
; RUN:  | FileCheck %s -check-prefix=EBC

@addr = global i8* null

define void @test_blockaddress() nounwind {
; EBC-LABEL: test_blockaddress:
; EBC:       ; %bb.0:
; EBC-NEXT:    push64 r1
; EBC-NEXT:    movrelq r7, Ltmp0
; EBC-NEXT:    movrelq r1, addr
; EBC-NEXT:    movqq @r1, r7
; EBC-NEXT:    movqq r7, @r1
; EBC-NEXT:  Ltmp0: ; Block address taken
; EBC-NEXT:  ; %bb.1: ; %block
; EBC-NEXT:    pop64 r1
; EBC-NEXT:    ret
  store volatile i8* blockaddress(@test_blockaddress, %block), i8** @addr
  %val = load volatile i8*, i8** @addr
  br label %block

block:
  ret void
}
