; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ebc -verify-machineinstrs < %s \
; RUN:  | FileCheck %s -check-prefix=EBC

define i64 @zero() nounwind {
; EBC-LABEL:  zero:
; EBC:        ; %bb.0:
; EBC-NEXT:     moviqq r7, 0
; EBC-NEXT:     ret
  ret i64 0
}

define i64 @pos_i64() nounwind {
; EBC-LABEL:  pos_i64:
; EBC:        ; %bb.0:
; EBC-NEXT:     moviqq r7, 2047
; EBC-NEXT:     ret
  ret i64 2047
}

define i64 @neg_i64() nounwind {
; EBC-LABEL:  neg_i64:
; EBC:        ; %bb.0:
; EBC-NEXT:     moviqq r7, -2048
; EBC-NEXT:     ret
  ret i64 -2048
}

define i32 @pos_i32() nounwind {
; EBC-LABEL:  pos_i32:
; EBC:        ; %bb.0:
; EBC-NEXT:     moviqq r7, 1735928559
; EBC-NEXT:     ret
  ret i32 1735928559
}

define i32 @neg_i32() nounwind {
; EBC-LABEL:  neg_i32:
; EBC:        ; %bb.0:
; EBC-NEXT:     moviqq r7, -559038737
; EBC-NEXT:     ret
  ret i32 -559038737
}

define i16 @pos_i16() nounwind {
; EBC-LABEL:  pos_i16:
; EBC:        ; %bb.0:
; EBC-NEXT:     moviqq r7, 65535
; EBC-NEXT:     ret
  ret i16 65535
}

define i16 @neg_i16() nounwind {
; EBC-LABEL:  neg_i16:
; EBC:        ; %bb.0:
; EBC-NEXT:     moviqq r7, -1234
; EBC-NEXT:     ret
  ret i16 -1234
}
