; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ebc -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=EBC

define i64 @zero() nounwind {
; EBC-LABEL: zero:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviww r7, 0
; EBC-NEXT:    ret
  ret i64 0
}

define i64 @imm64_1() nounwind {
; EBC-LABEL: imm64_1:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviww r7, 32767
; EBC-NEXT:    ret
  ret i64 32767
}

define i64 @imm64_2() nounwind {
; EBC-LABEL: imm64_2:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviww r7, -32768
; EBC-NEXT:    ret
  ret i64 -32768
}

define i64 @imm64_3() nounwind {
; EBC-LABEL: imm64_3:
; EBC:       ; %bb.0:
; EBC-NEXT:    movidd r7, 2147483647
; EBC-NEXT:    ret
  ret i64 2147483647
}

define i64 @imm64_4() nounwind {
; EBC-LABEL: imm64_4:
; EBC:       ; %bb.0:
; EBC-NEXT:    movidd r7, -2147483648
; EBC-NEXT:    ret
  ret i64 -2147483648
}

define i64 @imm64_5() nounwind {
; EBC-LABEL: imm64_5:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviqq r7, 9223372036854775807
; EBC-NEXT:    ret
  ret i64 9223372036854775807
}

define i64 @imm64_6() nounwind {
; EBC-LABEL: imm64_6:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviqq r7, -9223372036854775808
; EBC-NEXT:    ret
  ret i64 -9223372036854775808
}

define signext i32 @imm32_1() nounwind {
; EBC-LABEL: imm32_1:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviww r7, 32767
; EBC-NEXT:    ret
  ret i32 32767
}

define signext i32 @imm32_2() nounwind {
; EBC-LABEL: imm32_2:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviww r7, -32768
; EBC-NEXT:    ret
  ret i32 -32768
}

define signext i32 @imm32_3() nounwind {
; EBC-LABEL: imm32_3:
; EBC:       ; %bb.0:
; EBC-NEXT:    movidd r7, 2147483647
; EBC-NEXT:    ret
  ret i32 2147483647
}

define signext i32 @imm32_4() nounwind {
; EBC-LABEL: imm32_4:
; EBC:       ; %bb.0:
; EBC-NEXT:    movidd r7, -2147483648
; EBC-NEXT:    ret
  ret i32 -2147483648
}

define signext i16 @imm16_1() nounwind {
; EBC-LABEL: imm16_1:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviww r7, 32767
; EBC-NEXT:    ret
  ret i16 32767
}

define signext i16 @imm16_2() nounwind {
; EBC-LABEL: imm16_2:
; EBC:       ; %bb.0:
; EBC-NEXT:    moviww r7, -32768
; EBC-NEXT:    ret
  ret i16 -32768
}
