; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ebc -verify-machineinstrs < %s \
; RUN:  | FileCheck %s -check-prefix=EBC

define i64 @indirectbr(i8* %target) nounwind {
; EBC-LABEL: indirectbr:
; EBC:       ; %bb.0:
; EBC-NEXT:    movqw r7, r0 (0,8)
; EBC-NEXT:    movqq r7, @r7
; EBC-NEXT:    jmp32a @r7
; EBC-NEXT:  ; %bb.1: ; %test_label
; EBC-NEXT:    moviww r7, 0
; EBC-NEXT:    ret
  indirectbr i8* %target, [label %test_label]
test_label:
  br label %ret
ret:
  ret i64 0
}

define i64 @indirectbr_with_offset(i8* %a) nounwind {
; EBC-LABEL: indirectbr_with_offset:
; EBC:       ; %bb.0:
; EBC-NEXT:    movqw r0, r0 (0,-16)
; EBC-NEXT:    push64 r1
; EBC-NEXT:    movqw r7, r0 (0,24)
; EBC-NEXT:    movqq r7, @r7
; EBC-NEXT:    moviww r1, 1380
; EBC-NEXT:    add64 r7, r1
; EBC-NEXT:    jmp32a @r7
; EBC-NEXT:  ; %bb.1: ; %test_label
; EBC-NEXT:    moviww r7, 0
; EBC-NEXT:    pop64 r1
; EBC-NEXT:    movqw r0, r0 (0,16)
; EBC-NEXT:    ret
  %target = getelementptr inbounds i8, i8* %a, i64 1380
  indirectbr i8* %target, [label %test_label]
test_label:
  br label %ret
ret:
  ret i64 0
}
