; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ebc -verify-machineinstrs < %s \
; RUN:  | FileCheck %s -check-prefix=EBC

define i64 @load(i64 *%a) nounwind {
; EBC-LABEL:  load:
; EBC:        ; %bb.0:
; EBC-NEXT:     push64  r1
; EBC-NEXT:     movqw   r7, @r0 (-1,0)
; EBC-NEXT:     movqq   r7, @r7
; EBC-NEXT:     movqq   r1, @r7
; EBC-NEXT:     moviqq  r1, 24
; EBC-NEXT:     add64   r7, r1
; EBC-NEXT:     movqq   r7, @r7
; EBC-NEXT:     pop64   r1
; EBC-NEXT:     ret
  %1 = getelementptr i64, i64* %a, i64 3
  %2 = load i64, i64* %1
  %3 = load volatile i64, i64* %a
  ret i64 %2
}

define void @store(i64 *%a, i64 %b) nounwind {
; EBC-LABEL:    store:
; EBC:          ; %bb.0:
; EBC-NEXT:       push64  r1
; EBC-NEXT:       push64  r2
; EBC-NEXT:       movqw   r7, @r0 (-1,0)
; EBC-NEXT:       movqq   r7, @r7
; EBC-NEXT:       movqw   r1, @r0 (-2,0)
; EBC-NEXT:       movqq   r1, @r1
; EBC-NEXT:       movqq   @r1, r7
; EBC-NEXT:       moviqq  r2, 64
; EBC-NEXT:       add64   r7, r2
; EBC-NEXT:       movqq   @r1, r7
; EBC-NEXT:       pop64   r2
; EBC-NEXT:       pop64   r1
; EBC-NEXT:       ret
  store i64 %b, i64* %a
  %1 = getelementptr i64, i64* %a, i64 8
  store i64 %b, i64* %1
  ret void
}
